version: "3"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"

  catalog-history-service:
    image: ghcr.io/informasjonsforvaltning/catalog-history-service:staging_latest
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - MONGO_HOST=mongodb:27017
    ports:
      - "9090:8080"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=elasticpwd
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
