server.port: 8080
logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
spring:
  mongodb:
    host: ${MONGODB_HOST}
    username: ${MONGODB_USER}
    password: ${MONGODB_PASSWORD}
    authentication-database: ${MONGODB_AUTH}
    replica-set-name: ${MONGODB_REPLICASET}
    port: 27017
    database: conceptCatalog
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: ${KEYCLOAK_OIDC_ISSUER}/protocol/openid-connect/certs
    issuer-uri: ${KEYCLOAK_OIDC_ISSUER}
management:
  endpoints:
    web:
      path-mapping:
        info: ping
      exposure:
        include: health, info
  metrics:
    tags:
      application: concept-catalog
application:
  collectionBaseUri: ${COLLECTION_BASE_URI}
  historyServiceUri: ${CATALOG_HISTORY_SERVICE_URI}
  adminServiceUri: ${CATALOG_ADMIN_SERVICE_URI}
  harvestAdminUri: ${ADMIN_API_BASE_URI}
  cors.originPatterns: "${CORS_ORIGIN_PATTERNS}"
  elasticsearch:
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}
    host: ${ELASTIC_HOST}
    ssl: true
    storePath: ${ELASTIC_KEYSTORE_PATH}
    storePass: ${ELASTIC_KEYSTORE_PASSWORD}

---
spring:
  config.activate.on-profile: develop
  mongodb:
    host: localhost
    username: admin
    password: admin
    authentication-database: admin
    replica-set-name: null
  security.oauth2.resourceserver.jwt.jwk-set-uri: https://auth.staging.fellesdatakatalog.digdir.no/realms/fdk/protocol/openid-connect/certs
application:
  cors.originPatterns: "*"
  elasticsearch:
    username: elastic
    password: elasticpwd
    host: localhost:9200
    ssl: false

---
spring:
  config.activate.on-profile: contract-test
  main:
    allow-bean-definition-overriding: true
  mongodb:
    host: localhost
    username: testuser
    password: testpassword
    authentication-database: admin
    replica-set-name: null
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: http://localhost:6000/realms/fdk/protocol/openid-connect/certs
    issuer-uri: http://localhost:6000/realms/fdk
application:
  collectionBaseUri: https://concept-catalog.fellesdatakatalog.digdir.no
  historyServiceUri: http://localhost:6000
  adminServiceUri: http://localhost:6000
  harvestAdminUri: http://localhost:6000
  cors.originPatterns: "*"
  elasticsearch:
    username: elastic
    password: elasticpwd
    host: localhost:9200
    ssl: false
    storePath: path
    storePass: pass
