server.port: 8080
logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
spring:
  data.mongodb.uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/concept-catalogue?authSource=admin&authMechanism=SCRAM-SHA-1
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: ${SSO_HOST:https://sso.staging.fellesdatakatalog.digdir.no}/auth/realms/fdk/protocol/openid-connect/certs
    issuer-uri: ${SSO_HOST:https://sso.staging.fellesdatakatalog.digdir.no}/auth/realms/fdk
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME:admin}
    password: ${RABBIT_PASSWORD:admin}
management:
  endpoints:
    web:
      path-mapping:
        info: ping
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: concept-catalog
application:
  collectionBaseUri: ${COLLECTION_BASE_URI:https://concept-catalog.fellesdatakatalog.digdir.no}
  historyServiceUri: ${CATALOG_HISTORY_SERVICE_URI:http://localhost:9090}
  adminServiceUri: ${CATALOG_ADMIN_SERVICE_URI:https://catalog-admin-service.fellesdatakatalog.digdir.no}
  namespace: ${NAMESPACE:staging}

---
spring:
  config.activate.on-profile: develop
  data.mongodb.uri: mongodb://admin:admin@localhost:27017/datasetCatalog?authSource=admin&authMechanism=SCRAM-SHA-1
  security.oauth2.resourceserver.jwt.jwk-set-uri: https://sso.staging.fellesdatakatalog.digdir.no/auth/realms/fdk/protocol/openid-connect/certs
  rabbitmq.host: 127.0.0.1

---
spring:
  config.activate.on-profile: contract-test
  security.oauth2.resourceserver.jwt.jwk-set-uri: http://localhost:6000/auth/realms/fdk/protocol/openid-connect/certs
application:
  historyServiceUri: http://localhost:6000

