---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    fdk.service: concept-catalog
  name: concept-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: concept-catalog
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        fdk.service: concept-catalog
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      volumes:
        - name: elastic-certs
          secret:
            secretName: elasticsearch-es-http-certs-public
        - name: keystore-volume
          emptyDir:
            sizeLimit: 2Gi
      initContainers:
        - name: pem-to-keystore
          image: eclipse-temurin:17-jdk-alpine
          env:
            - name: crtfile
              value: /var/secrets/elastic/tls.crt
            - name: keystore_jks
              value: /var/secrets/elastic/keystores/keystore.jks
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: concept-catalog
                  key: KEYSTORE_PASSWORD
          command: ["/bin/sh"]
          args: ['-c', "keytool -noprompt -import -v -trustcacerts -file $crtfile -keystore $keystore_jks -keypass $KEYSTORE_PASSWORD -storepass $KEYSTORE_PASSWORD"]
          volumeMounts:
            - name: keystore-volume
              mountPath: /var/secrets/elastic/keystores
            - name: elastic-certs
              mountPath: /var/secrets/elastic
      containers:
        - name: concept-catalog
          env:
            - name: NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: common-prod
                  key: NAMESPACE
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: concept-catalog
                  key: MONGODB_USER
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: concept-catalog
                  key: MONGODB_PASSWORD
            - name: MONGODB_HOST
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGODB_HOST
            - name: MONGODB_REPLICASET
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGODB_REPLICASET
            - name: MONGODB_AUTH
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGODB_AUTH
            - name: COLLECTION_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: CONCEPT_CATALOG_BASE_URI
            - name: SSO_HOST
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: SSO_BASE_URI
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: RABBITMQ_USERNAME
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: RABBITMQ_PASSWORD
            - name: CATALOG_HISTORY_SERVICE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: CATALOG_HISTORY_SERVICE_HOST
            - name: CATALOG_ADMIN_SERVICE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: CATALOG_ADMIN_SERVICE_BASE_URI
            - name: ELASTIC_KEYSTORE_PATH
              value: /var/secrets/elastic/keystores/keystore.jks
            - name: ELASTIC_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: concept-catalog
                  key: KEYSTORE_PASSWORD
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: es-user-concept-catalog
                  key: username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: es-user-concept-catalog
                  key: password
            - name: ELASTIC_HOST
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-es
                  key: ELASTIC_HOST
            - name: CORS_ORIGIN_PATTERNS
              valueFrom:
                secretKeyRef:
                  name: concept-catalog
                  key: CORS_ORIGIN_PATTERNS
          image: concept-catalog
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "2Gi"
              cpu: "200m"
            limits:
              memory: "2Gi"
          volumeMounts:
            - name: keystore-volume
              mountPath: /var/secrets/elastic/keystores
      restartPolicy: Always    
