---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: concept-catalog
  name: concept-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: concept-catalog
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: concept-catalog
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: concept-catalog
          image: concept-catalog
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "2Gi"
              cpu: "200m"
            limits:
              memory: "2Gi"
      restartPolicy: Always    
