---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    fdk.service: concept-catalog
  name: concept-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: concept-catalog
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        fdk.service: concept-catalog
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      volumes:
        - name: elastic-certs
          secret:
            secretName: elasticsearch-es-http-certs-public
        - name: keystore-volume
          emptyDir:
            sizeLimit: 2Gi
      initContainers:
        - name: pem-to-keystore
          image: eclipse-temurin:17-jdk-alpine
          env:
            - name: crtfile
              value: /var/secrets/elastic/tls.crt
            - name: keystore_jks
              value: /var/secrets/elastic/keystores/keystore.jks
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: concept-catalog
                  key: KEYSTORE_PASSWORD
          command: ["/bin/sh"]
          args: ['-c', "keytool -noprompt -import -v -trustcacerts -file $crtfile -keystore $keystore_jks -keypass $KEYSTORE_PASSWORD -storepass $KEYSTORE_PASSWORD"]
          volumeMounts:
            - name: keystore-volume
              mountPath: /var/secrets/elastic/keystores
            - name: elastic-certs
              mountPath: /var/secrets/elastic
      containers:
        - name: concept-catalog
          image: concept-catalog
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "2Gi"
              cpu: "200m"
            limits:
              memory: "2Gi"
          volumeMounts:
            - name: keystore-volume
              mountPath: /var/secrets/elastic/keystores
      restartPolicy: Always    
