---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - concept-catalog-deployment.yaml
  - concept-catalog-service.yaml
images:
  - name: concept-catalog
    newName: ghcr.io/informasjonsforvaltning/concept-catalog
    newTag: $(GIT_COMMIT_SHA)
